### ISSUE TITLE
How are payloads generated?

### ISSUE THREAD

**Issue by 0x6d69636b** [federicodotta/Java-Deserialization-Scanner#13]
Hi,

I was wondering, how did you generate the initial payloads, e.g. _Hibernate 5 (Sleep)_. I tried to recreate those by using ysoserial without any luck. 

Thank you for your help!

**Comment by federicodotta** [comment]
Hi!

The payload are generated with a modified version of ysoserial that executes the sleep method instead of the exec one.  Refer to my fork of ysoserial for the code (it is old but the code should work).

Federico

**Comment by 0x6d69636b** [comment]
Thx Federico! Sadly I can't find the Hibernate 5 payload. Can you help me please to generate those...

**Comment by federicodotta** [comment]
Hi! I published my fork of ysoserial, that you can use to generate the native sleep and DNS payloads of the plugin. You can find the tool [here](https://github.com/federicodotta/ysoserial)

**Comment by 0x6d69636b** [comment]
Thank you for your effort Federico :) 👍 I will try your fork and I close this issue.
