### ISSUE TITLE
Add ruby deser. detection

### ISSUE THREAD

**Issue by dorkerdevil** [federicodotta/Java-Deserialization-Scanner#17]
Is it possible to add to detect ruby Deserialization  vulnerability

reference: https://www.elttam.com.au/blog/ruby-deserialization/

change the content type to
Content-Type:application/xml

and sending the gadget chain to test.

**Comment by federicodotta** [comment]
Hi!

thank you but the plugin is focused on Java. For the moment I will not add other languages.

Federico
