### ISSUE TITLE
Issue Installing Extension

### ISSUE THREAD

**Issue by Kaustav112** [federicodotta/Java-Deserialization-Scanner#18]
BApp Version -  1.7.36
While installing The extension you uploaded after cloning I am facing an error stating:
BApp Verification failed- The BApp may have been tampered with.

Please resolve this issue.

**Comment by federicodotta** [comment]
Hi @Kaustav112 ,

sorry but I can't replicate the issue. Do you have the same issue also on the new version? 

Federico
