### ISSUE TITLE
Java 8 payloads Generation

### ISSUE THREAD

**Issue by CyberRift** [federicodotta/Java-Deserialization-Scanner#20]
Hi,

Thank you for awesome extension, it is very helpful.

How did you generate Java 8 (with no library) payloads? could you please point me the tool you used?
ysoserial doesn't have java 8 payload.

Thanks.

**Comment by federicodotta** [comment]
Hi CyberRift,

The payload has been created by pwntester. You can find the code here:

https://github.com/pwntester/JRE8u20_RCE_Gadget

Federico
