### ISSUE TITLE
Incorrectly adds CRLF in front of content-length

### ISSUE THREAD

**Issue by ChrisAD** [federicodotta/Java-Deserialization-Scanner#25]
I have a hard time using the plugin because with Burp Suite v2021.4-6901 the plugin adds a CRLF in front of the tools own calculated content-length. It does also not replace any existing content-length. 

![1](https://user-images.githubusercontent.com/6368326/113721822-2579f880-96f0-11eb-88ca-7e990aa63a56.png)

**Comment by cactuschibre** [comment]
Same for me :/
