### ISSUE TITLE
How was the Rhino1 (Sleep) payload generated?

### ISSUE THREAD

**Issue by h1pmnh** [federicodotta/Java-Deserialization-Scanner#29]
Hi Federico,

I have been trying to reverse engineer some of the hard-coded payloads as a learning experience and I am stuck trying to figure out the Rhino1 (Sleep) payload. I attempted to modify the `MozillaRhino1` ysyoserial payload (actually, the `Gadgets.createTemplateImpl`) to create a Javassist class that invokes `java.lang.Thread.sleep(10000L)`.

This seems to work but the generated serialized payload is not exactly the same as the one used by the Burp plugin. Just wondering what I might be doing differently or if you have the original in a git repo somewhere :)

Thank you!
~~ Peter

**Comment by federicodotta** [comment]
Hi @h1pmnh,

You can find the code I used in my [fork of ysoserial](https://github.com/federicodotta/ysoserial), in which I added the code to generate sleep and DNS payloads.

Federico

**Comment by h1pmnh** [comment]
Ah clever, thank you! I will review your implementation. Appreciate it :)
